language: node_js
node_js:
  - 14
cache: npm

services:
  - auth
  - tickets
  - user

before_script:
  - npm install -g @nestjs/cli
  - cd 09-app-rmq
  - npm install

script:
  - npm run lint

# safelist
branches:
  only:
    - main
