version: "3.7"

volumes:
  postgres-data:

services:

  #### postgres
  postgres:
    container_name: postgres
    image: postgres:13
    restart: always
    ports: # for debug puproses, remove in the production
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user
      - PGPORT=5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  #### pgadmin
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: admin
